// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYXiOIJyR_8p87lOirH-OixciQ20UK7Ds',
    appId: '1:267722495735:web:760f450f45a3e9507fe5f2',
    messagingSenderId: '267722495735',
    projectId: 'chatapp-4c2f8',
    authDomain: 'chatapp-4c2f8.firebaseapp.com',
    storageBucket: 'chatapp-4c2f8.appspot.com',
    measurementId: 'G-8RMWSZ01SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcjm5sPBWYvWwLkxzib9O5roE_7WYXXf4',
    appId: '1:267722495735:android:95552b3afa5cdcef7fe5f2',
    messagingSenderId: '267722495735',
    projectId: 'chatapp-4c2f8',
    storageBucket: 'chatapp-4c2f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBja6N4VmssI_gzjMda_MtQLxqERk6bzcw',
    appId: '1:267722495735:ios:4928b212707d23d97fe5f2',
    messagingSenderId: '267722495735',
    projectId: 'chatapp-4c2f8',
    storageBucket: 'chatapp-4c2f8.appspot.com',
    iosBundleId: 'com.example.chatWithFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBja6N4VmssI_gzjMda_MtQLxqERk6bzcw',
    appId: '1:267722495735:ios:ee8b2e5cac00e28b7fe5f2',
    messagingSenderId: '267722495735',
    projectId: 'chatapp-4c2f8',
    storageBucket: 'chatapp-4c2f8.appspot.com',
    iosBundleId: 'com.example.chatWithFriends.RunnerTests',
  );
}
